version: 2.1

workflows:
  build_and_test:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - run: echo "Running Build"
